# Generated by Django 2.0.1 on 2018-03-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searcher.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searcher.Folder'),
        ),
    ]
