# Generated by Django 2.0.1 on 2018-03-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_auto_20180319_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='hashtags',
            new_name='tags',
        ),
    ]
