# Generated by Django 2.0.1 on 2018-03-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_auto_20180319_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
