# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0005_remove_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='folder',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
